### ISSUE TITLE
Question for Hodag Leather - Recharge Roll

### ISSUE THREAD

**Issue by RodiakWolfshain** [foundryvtt/pf2e#15570]
Shouldnt the recharge roll be visible? 
Since this is an Item for a players, they should know how long they cant use the item again. Shouldn't they?

**Comment by simonward** [comment]
This was fixed by https://github.com/foundryvtt/pf2e/pull/15150.  Try grabbing a fresh copy of the armor from the compendium.

**Comment by RodiakWolfshain** [comment]
I'm running currently PF 6.1.2 and - if I search for the Item directly in the compendium, I still get the hidden roll. 

![Screenshot 2024-07-25 163457](https://github.com/user-attachments/assets/dd7629aa-8937-4ae1-9a71-19cf0a372e17)
![Screenshot 2024-07-25 163548](https://github.com/user-attachments/assets/2fb2dabb-e55b-46ab-ba64-9969622947bb)

**Comment by simonward** [comment]
That's definitely an old copy, as the formatting is different.
<img width="625" alt="Screen Shot 2024-07-25 at 9 01 08 AM" src="https://github.com/user-attachments/assets/27b7460c-44d7-4d81-88c0-dbaad9e0cf7a">

<img width="295" alt="Screen Shot 2024-07-25 at 8 58 59 AM" src="https://github.com/user-attachments/assets/1788c9d6-b547-4baf-aa74-d90d3130134c">

**Comment by simonward** [comment]
Have you tried a fresh world with no modules?

**Comment by RodiakWolfshain** [comment]
Well... yeah... Fresh world - all good. 
Ok... Now, I can troubleshoot why the compendiums aren't updated, if there is a newer PF2 Version. Great.
Thanks Simon ;)
