### ISSUE TITLE
Flat modifiers to AC not working with predicates

### ISSUE THREAD

**Issue by isabroch** [foundryvtt/pf2e#7959]
The recent 4.12.0 update seems to have broken any flat modifiers to AC that use a toggle predicate. i.e. Warding Aggression, Nimble Dodge. Non-predicated bonuses seem to affect AC just fine though.

**Comment by stwlam** [comment]
Fixed by #7950

**Comment by isabroch** [comment]
Hello! I'd actually like to reopen this, as the bug is still applying for me? Warding Aggression is a status bonus and the toggle -is- checked on, but still not applying. Or do I make a new ticket?
![image](https://github.com/foundryvtt/pf2e/assets/43812480/7dd2fc9a-c050-4a35-aaa9-e40b6a684149)
![image](https://github.com/foundryvtt/pf2e/assets/43812480/e38a92a8-564e-43ca-ba33-3224131c46c9)

**Comment by stwlam** [comment]
OK, we'll take a look!
